spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8001}
  cloud:
    config:
      label: ${CONFIG_BRANCH:main}
      username: isavenok
      password: 1111

