server:
  port: 8001

spring:
  security:
    user:
      password: 1111
      name: isavenok
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI:https://github.com/savenok-ivan/simple-micro.git}
          username: ${REPO_USER:savenok.ivan@gmail.com}
          password: ${REPO_PASS:Azz244140}
          search-paths: configs
